### ISSUE TITLE
Respect key binding conventions

### ISSUE THREAD

**Issue by cocreature** [mpickering/hlint-refactor-mode#2]
Bindings consisting of C-c followed by a letter are reserved for custom bindings by users according to the [emacs key binding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). Imho it would be good to respect that, in fact `C-c a` is very often used for the orgmode agenda. I propose `C-c , b` and `C-c , r` for refactor buffer and refactor at point, but it's your mode so obviously it's up to you to decide :)

**Comment by mpickering** [comment]
Hi Moritz, thank you for your suggestion. I only use emacs for coq so I'm not sure what idiomatic bindings really look like. If you suggest that they would be better then that looks fine for me, I will change them as you suggest.
