### ISSUE TITLE
elpa

### ISSUE THREAD

**Issue by fatlazycat** [mpickering/hlint-refactor-mode#4]
Hi, is this packaged on elpa etc ?

Thanks

**Comment by cocreature** [comment]
It’s not yet on melpa. Feel free to submit it to melpa yourself following the instructions in the [readme](https://github.com/milkypostman/melpa).

If you don’t get to it I’ll do it when I have time.

**Comment by fatlazycat** [comment]
Looks pretty easy will try and give it a whirl shortly.

**Comment by fatlazycat** [comment]
Getting Warning: (error "Package lacks a file header") when building - will look at adding one

**Comment by fatlazycat** [comment]
https://github.com/milkypostman/melpa/pull/3320

**Comment by cocreature** [comment]
thanks :+1:

**Comment by fatlazycat** [comment]
Rather duplication but https://github.com/milkypostman/melpa/pull/3320#issuecomment-159179284

You guys happy to make the changes ?

**Comment by cocreature** [comment]
I'll make the necessary changes later today.

**Comment by mpickering** [comment]
I would prefer not to rename it to `hlint-refactor` as then I think it's confusing why only the emacs bindings live here. What do people usually do?

**Comment by cocreature** [comment]
We can leave the repo name and add a note to the readme. This is mostly about the naming of the files and some functions, but if you’re at a point where you take a look at those, you already know that it’s an emacs mode.

**Comment by cocreature** [comment]
See https://github.com/milkypostman/melpa/commit/79363587b07f68e30a98698fd33ab39153bcb06c
